"""
AgroPredict - SQLAlchemy Models for commodity price data.

Tables:
- Commodity: supported agricultural commodities
- Mandi: regulated market locations
- PriceObservation: daily commodity prices from AGMARKNET
- WeatherObservation: daily weather from Open-Meteo
"""

from datetime import date

# pyrefly: ignore [missing-import]
from sqlalchemy import (
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
)
# pyrefly: ignore [missing-import]
from sqlalchemy.orm import relationship

from app.core.database import Base


class Commodity(Base):
    """Agricultural commodity (e.g., Onion, Potato, Tomato, Tur Dal)."""

    __tablename__ = "commodities"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100), nullable=False, unique=True)
    slug = Column(String(100), nullable=False, unique=True)

    # Relationships
    price_observations = relationship(
        "PriceObservation", back_populates="commodity", lazy="selectin"
    )

    def __repr__(self) -> str:
        return f"<Commodity(id={self.id}, name='{self.name}')>"


class Mandi(Base):
    """Regulated agricultural market (mandi) location."""

    __tablename__ = "mandis"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100), nullable=False)
    state = Column(String(100), nullable=False)
    district = Column(String(100), nullable=False)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)

    # Unique on name + district to avoid duplicates
    __table_args__ = (
        UniqueConstraint("name", "district", name="uq_mandi_name_district"),
    )

    # Relationships
    price_observations = relationship(
        "PriceObservation", back_populates="mandi", lazy="selectin"
    )
    weather_observations = relationship(
        "WeatherObservation", back_populates="mandi", lazy="selectin"
    )

    def __repr__(self) -> str:
        return f"<Mandi(id={self.id}, name='{self.name}', district='{self.district}')>"


class PriceObservation(Base):
    """
    Daily commodity price observation from a mandi.

    Prices are in INR per quintal (100 kg) as reported by AGMARKNET.
    Idempotency enforced at DB level via unique constraint on
    (commodity_id, mandi_id, date).
    """

    __tablename__ = "price_observations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    commodity_id = Column(
        Integer, ForeignKey("commodities.id"), nullable=False, index=True
    )
    mandi_id = Column(
        Integer, ForeignKey("mandis.id"), nullable=False, index=True
    )
    date = Column(Date, nullable=False, index=True)
    min_price = Column(Float, nullable=True)
    max_price = Column(Float, nullable=True)
    modal_price = Column(Float, nullable=True)
    arrival_qty = Column(Float, nullable=True)  # in tonnes
    variety = Column(String(100), nullable=True, default="FAQ")
    grade = Column(String(100), nullable=True, default="FAQ")

    # Enforce idempotency at DB level
    __table_args__ = (
        UniqueConstraint(
            "commodity_id",
            "mandi_id",
            "date",
            name="uq_price_commodity_mandi_date",
        ),
    )

    # Relationships
    commodity = relationship("Commodity", back_populates="price_observations")
    mandi = relationship("Mandi", back_populates="price_observations")

    def __repr__(self) -> str:
        return (
            f"<PriceObservation(commodity_id={self.commodity_id}, "
            f"mandi_id={self.mandi_id}, date={self.date}, "
            f"modal_price={self.modal_price})>"
        )


class WeatherObservation(Base):
    """
    Daily weather observation for a mandi location.

    Data sourced from Open-Meteo historical/archive API.
    Idempotency enforced via unique constraint on (mandi_id, date).
    """

    __tablename__ = "weather_observations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    mandi_id = Column(
        Integer, ForeignKey("mandis.id"), nullable=False, index=True
    )
    date = Column(Date, nullable=False, index=True)
    temp_max = Column(Float, nullable=True)  # Celsius
    temp_min = Column(Float, nullable=True)  # Celsius
    precipitation_mm = Column(Float, nullable=True)  # millimeters

    # Enforce idempotency at DB level
    __table_args__ = (
        UniqueConstraint(
            "mandi_id", "date", name="uq_weather_mandi_date"
        ),
    )

    # Relationships
    mandi = relationship("Mandi", back_populates="weather_observations")

    def __repr__(self) -> str:
        return (
            f"<WeatherObservation(mandi_id={self.mandi_id}, "
            f"date={self.date}, temp_max={self.temp_max})>"
        )


class ForecastLog(Base):
    """
    Log of individual serving forecasts generated by the system.
    Used for drift detection and accuracy tracking.
    """
    __tablename__ = "forecast_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    commodity_id = Column(Integer, ForeignKey("commodities.id"), nullable=False, index=True)
    mandi_id = Column(Integer, ForeignKey("mandis.id"), nullable=False, index=True)
    forecast_date = Column(Date, nullable=False, index=True) # Date we are predicting
    created_at = Column(DateTime, nullable=False, index=True) # When we ran prediction
    p10 = Column(Float, nullable=False)
    p50 = Column(Float, nullable=False)
    p90 = Column(Float, nullable=False)
    model_name = Column(String(50), nullable=False)

    # Relationships
    commodity = relationship("Commodity")
    mandi = relationship("Mandi")


class ForecastAccuracy(Base):
    """
    Daily accuracy metrics computed retrospectively.
    Converts ForecastLog + PriceObservation into MAE, RMSE, MAPE.
    """
    __tablename__ = "forecast_accuracies"

    id = Column(Integer, primary_key=True, autoincrement=True)
    commodity_id = Column(Integer, ForeignKey("commodities.id"), nullable=False, index=True)
    mandi_id = Column(Integer, ForeignKey("mandis.id"), nullable=False, index=True)
    eval_date = Column(Date, nullable=False, index=True)
    model_name = Column(String(50), nullable=False)
    horizon = Column(Integer, nullable=False) # e.g. 7 or 30
    mae = Column(Float, nullable=False)
    rmse = Column(Float, nullable=False)
    mape = Column(Float, nullable=False)

    # Relationships
    commodity = relationship("Commodity")
    mandi = relationship("Mandi")


class User(Base):
    """System users who can log in and save their forecast query history."""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String(50), nullable=False, unique=True, index=True)
    password_hash = Column(String(255), nullable=False)


class UserQueryLog(Base):
    """Log of searches/queries executed by a logged-in user."""
    __tablename__ = "user_query_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    commodity_slug = Column(String(100), nullable=False)
    mandi_name = Column(String(100), nullable=False)
    state = Column(String(100), nullable=False)
    district = Column(String(100), nullable=False)
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    created_at = Column(DateTime, nullable=False, index=True)

    # Relationships
    user = relationship("User")

